
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = "de-DE" | "default" | "es-ES";

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
  | "article"
  | "blog_post"
  | "call_to_action"
  | "cta_card"
  | "disclaimer"
  | "event"
  | "faq_section"
  | "infograph_section"
  | "infograph"
  | "landing_page"
  | "page"
  | "person"
  | "question___answer"
  | "service"
  | "testimonial_section"
  | "testimonial"
  | "three_card_cta"
  | "video";

/**
 * Type representing all collections
 */
export type CollectionCodenames =
  | "academic_content"
  | "default"
  | "ecommerce"
  | "hub"
  | "operations"
  | "patient_resources"
  | "website";

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = "academic_resources" | "biographies" | "default" | "patient_resources";

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames =
  | "article_type"
  | "event_topic"
  | "event_type"
  | "general_healthcare_topics"
  | "medical_specialties";

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames =
  | "archived"
  | "copy_review"
  | "draft_97d445e"
  | "draft_a8b162c"
  | "draft_b242d4d"
  | "draft"
  | "legal_review"
  | "marketing_review"
  | "medical_review"
  | "peer_review"
  | "published"
  | "reviewed_1778942"
  | "reviewed"
  | "scheduled"
  | "staff_member_review"
  | "translation";

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
  | "answer"
  | "article_type"
  | "author"
  | "autoplay"
  | "background_image"
  | "biography"
  | "body_copy"
  | "body"
  | "button_label"
  | "button_link"
  | "button_text"
  | "caption"
  | "card_ctas"
  | "description"
  | "email"
  | "end_date"
  | "event_topic"
  | "event_type"
  | "featured_content"
  | "first_name"
  | "guidelines"
  | "header"
  | "heading"
  | "headline"
  | "hero_image"
  | "hero_link"
  | "image_position"
  | "image"
  | "infographics"
  | "introduction"
  | "job_title"
  | "last_name"
  | "medical_specialties"
  | "metadata__description"
  | "metadata__keywords"
  | "metadata__title"
  | "metadata"
  | "name"
  | "phone"
  | "prefix"
  | "publish_date"
  | "question_and_answers"
  | "question"
  | "quote"
  | "related_articles"
  | "role"
  | "start_date"
  | "style"
  | "subheadline"
  | "subpages"
  | "suffixes"
  | "summary"
  | "team"
  | "testimonials"
  | "title"
  | "topics"
  | "type"
  | "url_slug"
  | "url"
  | "video_link"
  | "website";
