
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * CTA Card
 *
 * Id: ec18e022-aab4-48ea-a1d3-7c20cfbba89c
 * Codename: cta_card
 */
export type CTACard = CoreContentType<
  CTACardElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: false
     * Codename: headline
     * Id: c8cafce6-2439-4639-ba01-760d69f538a2
     */
    readonly headline: Elements.TextElement;
    /**
     * Subheadline
     *
     * Type: text
     * Required: false
     * Codename: subheadline
     * Id: 1aa1ec85-ebdd-4021-bcde-cc4758496dda
     */
    readonly subheadline: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: false
     * Codename: image
     * Id: a884575c-b298-4052-b5f7-d68242a9bcfb
     */
    readonly image: Elements.AssetsElement;
  },
  "cta_card"
>;

/**
 * Type representing all available element codenames for CTA Card
 */
export type CTACardElementCodenames = "headline" | "subheadline" | "image";

/**
 * Type guard for CTA Card
 *
 * Id: ec18e022-aab4-48ea-a1d3-7c20cfbba89c
 * Codename: cta_card
 */
export function isCTACard(item: CoreContentType | undefined | null): item is CTACard {
  return item?.system?.type === "cta_card";
}
