
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { QuestionAnswer } from "./index.ts";

/**
 * FAQ Section
 *
 * Id: cd0a938b-d6ff-4aeb-a4bf-3a36e54a20ae
 * Codename: faq_section
 */
export type FAQSection = CoreContentType<
  FAQSectionElementCodenames,
  {
    /**
     * Heading
     *
     * Type: text
     * Required: false
     * Codename: heading
     * Id: 756074a1-b515-47c0-904c-52439a325393
     */
    readonly heading: Elements.TextElement;
    /**
     * Question and Answers
     *
     * Type: modular_content
     * Required: false
     * Codename: question_and_answers
     * Id: 53e761c4-d845-49f5-9f26-bcfe76af38af
     */
    readonly question_and_answers: Elements.LinkedItemsElement<QuestionAnswer>;
  },
  "faq_section"
>;

/**
 * Type representing all available element codenames for FAQ Section
 */
export type FAQSectionElementCodenames = "heading" | "question_and_answers";

/**
 * Type guard for FAQ Section
 *
 * Id: cd0a938b-d6ff-4aeb-a4bf-3a36e54a20ae
 * Codename: faq_section
 */
export function isFAQSection(item: CoreContentType | undefined | null): item is FAQSection {
  return item?.system?.type === "faq_section";
}
