
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Infograph
 *
 * Id: c231fc83-c81c-4b99-a8fd-bcd02e3b4389
 * Codename: infograph
 */
export type Infograph = CoreContentType<
  InfographElementCodenames,
  {
    /**
     * Image
     *
     * Type: asset
     * Required: false
     * Codename: image
     * Id: 9dd16bb4-5fea-4910-b604-6228d107fc79
     */
    readonly image: Elements.AssetsElement;
    /**
     * Body
     *
     * Type: text
     * Required: false
     * Codename: body
     * Id: 47e75448-4d5c-446e-aff1-159f34156b90
     */
    readonly body: Elements.TextElement;
  },
  "infograph"
>;

/**
 * Type representing all available element codenames for Infograph
 */
export type InfographElementCodenames = "image" | "body";

/**
 * Type guard for Infograph
 *
 * Id: c231fc83-c81c-4b99-a8fd-bcd02e3b4389
 * Codename: infograph
 */
export function isInfograph(item: CoreContentType | undefined | null): item is Infograph {
  return item?.system?.type === "infograph";
}
