
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Infograph } from "./index.ts";

/**
 * Infograph Section
 *
 * Id: bc659103-01b1-4c6c-8a62-a96c589ac540
 * Codename: infograph_section
 */
export type InfographSection = CoreContentType<
  InfographSectionElementCodenames,
  {
    /**
     * Header
     *
     * Type: text
     * Required: true
     * Codename: header
     * Id: 8599fadd-bda9-437d-acc3-742dd14f1694
     */
    readonly header: Elements.TextElement;
    /**
     * Infographics
     *
     * Type: modular_content
     * Required: true
     * Codename: infographics
     * Id: 52e86c46-88a0-4875-ae7e-df184ee59b23
     */
    readonly infographics: Elements.LinkedItemsElement<Infograph>;
  },
  "infograph_section"
>;

/**
 * Type representing all available element codenames for Infograph Section
 */
export type InfographSectionElementCodenames = "header" | "infographics";

/**
 * Type guard for Infograph Section
 *
 * Id: bc659103-01b1-4c6c-8a62-a96c589ac540
 * Codename: infograph_section
 */
export function isInfographSection(item: CoreContentType | undefined | null): item is InfographSection {
  return item?.system?.type === "infograph_section";
}
