
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type { Video, Disclaimer, CTA, Event, Article, Page } from "./index.ts";

/**
 * Landing Page
 *
 * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
 * Codename: landing_page
 */
export type LandingPage = CoreContentType<
  LandingPageElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: true
     * Codename: headline
     * Id: 19b37bc8-cd8a-43a2-a647-61732524abed
     */
    readonly headline: Elements.TextElement;
    /**
     * Subheadline
     *
     * Type: text
     * Required: true
     * Codename: subheadline
     * Id: 1f3be25d-1bcf-4e59-9003-14490f82f338
     */
    readonly subheadline: Elements.TextElement;
    /**
     * Hero Image
     *
     * Type: asset
     * Required: true
     * Codename: hero_image
     * Id: 5030bc21-47d3-451f-b5e7-d59d8d7a2439
     */
    readonly hero_image: Elements.AssetsElement;
    /**
     * Body Copy
     *
     * Type: rich_text
     * Required: false
     * Codename: body_copy
     * Id: 7b9826ff-5cb0-450f-b16a-bd176aed04cf
     */
    readonly body_copy: Elements.RichTextElement<Video | Disclaimer | CTA>;
    /**
     * Featured Content
     *
     * Type: modular_content
     * Required: false
     * Codename: featured_content
     * Id: 38cf004b-3054-43ff-9b7a-f0734b1d35f1
     */
    readonly featured_content: Elements.LinkedItemsElement<Event | Article | CTA>;
    /**
     * Button Text
     *
     * Type: text
     * Required: false
     * Codename: button_text
     * Id: fae1179a-4e1e-45e5-85c4-253d47bbfd80
     */
    readonly button_text: Elements.TextElement;
    /**
     * Hero Link
     *
     * Type: modular_content
     * Required: false
     * Codename: hero_link
     * Id: e6a8ed4a-5c19-475b-aae8-d22251e16a32
     */
    readonly hero_link: Elements.LinkedItemsElement<Page>;
    /**
     * Subpages
     *
     * Type: subpages
     * Required: false
     * Codename: subpages
     * Id: 9d5080db-f2bb-41a1-bcbe-11786ee3a59d
     */
    readonly subpages: Elements.LinkedItemsElement<Page>;
  } & Metadata,
  "landing_page"
>;

/**
 * Type representing all available element codenames for Landing Page
 */
export type LandingPageElementCodenames =
  | "headline"
  | "subheadline"
  | "hero_image"
  | "body_copy"
  | "featured_content"
  | "button_text"
  | "hero_link"
  | "subpages"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description";

/**
 * Type guard for Landing Page
 *
 * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
 * Codename: landing_page
 */
export function isLandingPage(item: CoreContentType | undefined | null): item is LandingPage {
  return item?.system?.type === "landing_page";
}
