
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Question + Answer
 *
 * Id: 0a593071-4a80-4ae0-ab94-7b56cc5ee4b8
 * Codename: question___answer
 */
export type QuestionAnswer = CoreContentType<
  QuestionAnswerElementCodenames,
  {
    /**
     * Question
     *
     * Type: text
     * Required: false
     * Codename: question
     * Id: 89823741-d788-4fb1-b181-913c818b64d8
     */
    readonly question: Elements.TextElement;
    /**
     * Answer
     *
     * Type: text
     * Required: false
     * Codename: answer
     * Id: 3b194514-18f9-446c-9820-efe7381189a2
     */
    readonly answer: Elements.TextElement;
  },
  "question___answer"
>;

/**
 * Type representing all available element codenames for Question + Answer
 */
export type QuestionAnswerElementCodenames = "question" | "answer";

/**
 * Type guard for Question + Answer
 *
 * Id: 0a593071-4a80-4ae0-ab94-7b56cc5ee4b8
 * Codename: question___answer
 */
export function isQuestionAnswer(item: CoreContentType | undefined | null): item is QuestionAnswer {
  return item?.system?.type === "question___answer";
}
