
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Testimonial } from "./index.ts";

/**
 * Testimonial Section
 *
 * Id: 2be53af7-701a-43e7-aafd-2843f8b3c6b8
 * Codename: testimonial_section
 */
export type TestimonialSection = CoreContentType<
  TestimonialSectionElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: 20fe2f69-777d-46f2-ab16-0e9ba8588755
     */
    readonly title: Elements.TextElement;
    /**
     * Testimonials
     *
     * Type: modular_content
     * Required: true
     * Codename: testimonials
     * Id: 627f8f30-64db-4401-a9a6-6fe03307e3c9
     */
    readonly testimonials: Elements.LinkedItemsElement<Testimonial>;
    /**
     * Background Image
     *
     * Type: asset
     * Required: false
     * Codename: background_image
     * Id: 9d0f9133-ac26-46de-ba0c-7b6b8ace2e6a
     */
    readonly background_image: Elements.AssetsElement;
  },
  "testimonial_section"
>;

/**
 * Type representing all available element codenames for Testimonial Section
 */
export type TestimonialSectionElementCodenames = "title" | "testimonials" | "background_image";

/**
 * Type guard for Testimonial Section
 *
 * Id: 2be53af7-701a-43e7-aafd-2843f8b3c6b8
 * Codename: testimonial_section
 */
export function isTestimonialSection(item: CoreContentType | undefined | null): item is TestimonialSection {
  return item?.system?.type === "testimonial_section";
}
