
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Testimonial
 *
 * Id: 9212aa9a-dee2-4c4d-bf95-f54a3c1d06b2
 * Codename: testimonial
 */
export type Testimonial = CoreContentType<
  TestimonialElementCodenames,
  {
    /**
     * Quote
     *
     * Type: text
     * Required: false
     * Codename: quote
     * Id: 7b1dc5dd-795e-42b5-a651-fe5a61915569
     */
    readonly quote: Elements.TextElement;
    /**
     * Name
     *
     * Type: text
     * Required: false
     * Codename: name
     * Id: 2591fc10-f54c-44a6-9210-043dccf8f0d0
     */
    readonly name: Elements.TextElement;
    /**
     * Role
     *
     * Type: text
     * Required: false
     * Codename: role
     * Id: 6b2a86a5-24b5-4856-a063-c73fc8679646
     */
    readonly role: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: false
     * Codename: image
     * Id: 4410630e-0869-41c2-913c-ba5107e12409
     */
    readonly image: Elements.AssetsElement;
  },
  "testimonial"
>;

/**
 * Type representing all available element codenames for Testimonial
 */
export type TestimonialElementCodenames = "quote" | "name" | "role" | "image";

/**
 * Type guard for Testimonial
 *
 * Id: 9212aa9a-dee2-4c4d-bf95-f54a3c1d06b2
 * Codename: testimonial
 */
export function isTestimonial(item: CoreContentType | undefined | null): item is Testimonial {
  return item?.system?.type === "testimonial";
}
