
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 💊 USANA
* Environment: Production
* Id: f8fe0228-0413-0023-9e3f-133ff815f2e3
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { CTACard } from "./index.ts";

/**
 * Three Card CTA
 *
 * Id: 5b99d6b6-32b3-42e7-acdd-01715d9a132d
 * Codename: three_card_cta
 */
export type ThreeCardCTA = CoreContentType<
  ThreeCardCTAElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: false
     * Codename: headline
     * Id: badd420d-8736-459d-87e0-73f9a73e7f10
     */
    readonly headline: Elements.TextElement;
    /**
     * Card CTAs
     *
     * Type: modular_content
     * Required: true
     * Codename: card_ctas
     * Id: 8d2aafd6-2993-461a-84e0-c82e9bed19b4
     */
    readonly card_ctas: Elements.LinkedItemsElement<CTACard>;
  },
  "three_card_cta"
>;

/**
 * Type representing all available element codenames for Three Card CTA
 */
export type ThreeCardCTAElementCodenames = "headline" | "card_ctas";

/**
 * Type guard for Three Card CTA
 *
 * Id: 5b99d6b6-32b3-42e7-acdd-01715d9a132d
 * Codename: three_card_cta
 */
export function isThreeCardCTA(item: CoreContentType | undefined | null): item is ThreeCardCTA {
  return item?.system?.type === "three_card_cta";
}
